@startuml
package "core/services" {
  node "DI Container" as DI
  node "Theme Service" as Theme
  node "Feature Flags Service" as FF
}

' Module nodes
package "modules 1" {
  node "Cart Module" as Cart
}

package "modules 2" {
  node "Popular Products Module" as Products
}

node "App.tsx" as App

' Dependencies
' DI --> Theme: manages
' DI --> FF: manages
' DI --> Cart: manages
' DI --> Products: manages

App ---> DI: register modules
App ---> Theme: init theme
App ---> Cart
App ---> Products

Products --> Cart: adds to cart
' Products --> Theme: uses
' Products --> FF: uses
@enduml
